// export default {
//   "Home Decor": "",
//   "Food and Drink": "",
//   "Hair and Beauty": "",
//   Humor: "",
//   Education: "",
//   Art: "",
//   Quotes: "",
//   Travel: "",
//   Design: "",
//   "DIY Home Decor": "",
//   Animals: "",
//   Makeup: "",
//   HairStyles: "",
//   Recipes: "",
//   Braids: "",
//   "Health and Fitness": "",
//   Photography: "",
//   Gardening: "",
//   Weddings: "",
//   Furniture: "",
//   Fitness: "",
//   "Ab Workouts": "",
//   "Geek Culture": "",
//   History: "",
//   "Abandoned Mansions": "",
//   Nails: "",
//   woodworking: "",
//   "Grilling Recipes": "",
//   Technology: "",
//   "Tattos and Bodyart": "",
//   "Eye Makeup": "",
//   "Survival Skills": "",
//   Fashion: "",
//   "Inspiration Quotes": "",
//   Memes: "",
//   "Skin Care": "",
//   "DIY Christmas Gifts": "",
//   Celebrities: "",
//   Desserts: "",
//   Gadgets: "",
//   Christmas: "",
//   "Backyard Ideas": "",
//   Architecture: "",
//   Shoes: "",
//   "DIY and Crafts": "",
//   "Life Quotes": "",
//   "Sports Cars": "",
//   "Home Renovation": "",
//   Pranks: "",
//   Camping: "",
//   "Country Weddings": "",
//   Disney: "",
//   "Black Hairstyles": "",
//   Birhtdays: "",
//   "Christmas Decor": "",
//   Cats: "",
//   "Long Hair": "",
//   "Star Wars": "",
//   "Easy Crafts": "",
//   "DIY Gifts": "",
//   Kittens: "",
//   "Sandwich Ideas": "",
//   "Short Hairstyle": "",
//   "Emo Fashion": "",
//   "DIY Home Crafts": "",
//   "Luxury Cars": "",
//   "Casual Outfits": "",
//   "Christmas Crafts": "",
//   "Healthy Snacks": "",
//   Cheer: "",
//   "American History": "",
//   Nutrition: "",
//   "Bedroom Ideas": "",
//   Dresses: "",
//   Drawings: "",
//   "Teen Girl Bedrooms": "",
//   "Crafts for Kids": "",
//   Relationships: "",
//   "Clean Eating": "",
//   Nascar: "",
//   Crafts: "",
//   Parenting: "",
//   "Baby Showers": "",
//   Landscapings: "",
//   Jordans: "",
//   "Kid Crafts": "",
//   Gift: "",
//   Ideas: "",
//   Cocktail: "",
//   "Girl Rooms": "",
//   "Walking Dead": "",
//   Vintage: "",
//   Yoga: "",
//   "Garden Design": "",
//   "Urban Gardening": ""
// };

export default [
  "Home Decor",
  "Food and Drink",
  "Hair and Beauty",
  "Humor",
  "Education",
  "Art",
  "Quotes",
  "Travel",
  "Design",
  "DIY Home Decor",
  "Animals",
  "Makeup",
  "HairStyles",
  "Recipes",
  "Braids",
  "Health and Fitness",
  "Photography",
  "Gardening",
  "Weddings",
  "Furniture",
  "Fitness",
  "Ab Workouts",
  "Geek Culture",
  "History",
  "Abandoned Mansions",
  "Nails",
  "woodworking",
  "Grilling Recipes",
  "Technology",
  "Tattos and Bodyart",
  "Eye Makeup",
  "Survival Skills",
  "Fashion",
  "Inspiration Quotes",
  "Memes",
  "Skin Care",
  "DIY Christmas Gifts",
  "Celebrities",
  "Desserts",
  "Gadgets",
  "Christmas",
  "Backyard Ideas",
  "Architecture",
  "Shoes",
  "DIY and Crafts",
  "Life Quotes",
  "Sports Cars",
  "Home Renovation",
  "Pranks",
  "Camping",
  "Country Weddings",
  "Disney",
  "Black Hairstyles",
  "Birhtdays",
  "Christmas Decor",
  "Cats",
  "Long Hair",
  "Star Wars",
  "Easy Crafts",
  "DIY Gifts",
  "Kittens",
  "Sandwich Ideas",
  "Short Hairstyle",
  "Emo Fashion",
  "DIY Home Crafts",
  "Luxury Cars",
  "Casual Outfits",
  "Christmas Crafts",
  "Healthy Snacks",
  "Cheer",
  "American History",
  "Nutrition",
  "Bedroom Ideas",
  "Dresses",
  "Drawings",
  "Teen Girl Bedrooms",
  "Crafts for Kids",
  "Relationships",
  "Clean Eating",
  "Nascar",
  "Crafts",
 " Parenting",
  "Baby Showers",
  "Landscapings",
  "Jordans",
  "Kid Crafts",
  "Gift",
  "Ideas",
  "Cocktail",
  "Girl Rooms",
  "Walking Dead",
  "Vintage",
  "Yoga",
  "Garden Design",
  "Urban Gardening"
];

